### ISSUE TITLE
write wrapper function like `hubEvals::score_model_out()` 

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubEvals#13]
- input: hubverse model_output_tbl, target_data, rules (optional), scale (`c("identity", "log")`), ...
    - action: check to ensure that all data are one output_type
    - action: translate model_output data to scoringutils objects
    - action: transform scoringutils object if specified
    - action:  call `scoringutils::score()`
    - (action: validate that rules can be applied to the model_output data type provided)
- output: `data.table` or `scores` object containing the scores

migrated from https://github.com/epiforecasts/scoringutils/issues/605

**Comment by nickreich** [comment]
Noting that this will require some standard understanding of hubverse target data, discussed in this issue here: https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/discussions/69

**Comment by elray1** [comment]
would be nice to have this name omit the same set of vowels as `model_out_tbl`

**Comment by nickreich** [comment]
Noting that per [this comment](https://github.com/orgs/Infectious-Disease-Modeling-Hubs/discussions/9#discussioncomment-8944609), we could assume a specific structure for the target data.

**Comment by nickreich** [comment]
In response to Evan's comment above, here are a few additional thoughts/comments about structure that might be needed for this:

1. we likely want the function to have a `by` argument that specifies which task-id variables to group by when returning results.
2. we should be clear what what hubverse output types can be used which which scoringutils metrics. See more info [here](https://epiforecasts.io/scoringutils/articles/metric-details.html).

**Comment by elray1** [comment]
Some notes on proposed updates to what's scoped out in the comment at top of this issue:

- scoringutils now uses `metrics` instead of `rules`, let's follow their lead
- I propose to move handling of transformations out to a different issue. I'm pretty sure this is not implemented for pmf forecasts? would rather think about it separately from the rest of this.
- eventually, it seems like it would be more convenient for the user if they could just pass in a data frame with multiple output types and get some scores back...
